import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import ReactQueryClientProvider from 'config/ReactQueryClientProvider';
import RecoilProvider from 'config/RecoilProvider';
import Auth from 'components/auth';
import MainLayout from 'components/layouts/main-layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const loggedIn = true;

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className="">
        <RecoilProvider>
          <ReactQueryClientProvider>
            {loggedIn ? <MainLayout>{children}</MainLayout> : <Auth />}
          </ReactQueryClientProvider>
        </RecoilProvider>
      </body>
    </html>
  );
}
